#!/bin/busybox sh

/bin/busybox mkdir -p /proc /sys /dev /sbin /usr/bin /usr/sbin
/bin/busybox --install -s

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Keep PID 1 alive in a shell if there is no real rootfs to switch to.
exec /bin/sh
